### ISSUE TITLE
Many links no longer work

### ISSUE THREAD

**Issue by mchurchward** [tsugiproject/tsugi#32]
I just upgraded to the latest version and now many of the links in the UI no longer work. This seems to be due to the fact that ".php" is missing from the URL's. For example, the upgrade link on the main page is "/admin/upgrade", and when I click it, gives a "not found" error.
Was there a change that required me to reconfigure something so that ".php" was inferred?

**Comment by csev** [comment]
Mike - I am moving toward requiring requiring mod_rewrite in order to make the URLs "pretter" so we avoid being criticised by all the fancy framework folks with pretty URLs (i.e.Rails, Cake, etc.)  These non-PHP urls should work because of the tsugi/.htaccess and tsugi/route.php files - but they require either mod_rewrite or a mod_dir > Apache 2.5 and permission to use mod_rewrite- Carl LeBlond fixed it this way:

https://groups.google.com/a/apereo.org/d/msg/tsugi-dev/K1Dty1ujk4o/w4tbMO5JAgAJ

**Comment by csev** [comment]
You probably want to be on the tsugi dev list - where I announce these things and work through any issues raised.

https://groups.google.com/a/apereo.org/forum/#!forum/tsugi-dev

**Comment by csev** [comment]
Mike,  I updated all the .htaccess files to add 

<IfModule mod_negotiation.c>
    Options -MultiViews
</IfModule>

You might want to try this too.  Or do a git pull.

**Comment by mchurchward** [comment]
Thanks Chuck. I'll take a look at this soon.

**Comment by mchurchward** [comment]
Hmmm... I already have mod_rewrite enabled.
Yep. It was the "AllowOverride" directive.
